# Generated by Django 2.2.6 on 2019-11-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
